# Dockerfile para o frontend UniFECAF
FROM python:3.11-slim

WORKDIR /frontend

COPY ../frontend/ ./

# Instala dependências mínimas para rodar o servidor
RUN pip install --no-cache-dir flask

EXPOSE 5001

CMD ["python", "server.py"] 